### ISSUE TITLE
3.5+ Support

### ISSUE THREAD

**Issue by shanegriffiths** [andrewfiorillo/sketch-character-count#2]
Hello, can you confirm that this plugin works in 3.5+ (before I upgrade).

Many thanks

**Comment by andrewfiorillo** [comment]
Sure, I'm running Sketch 3.5.2 and it appears to work fine.

**Comment by andrewfiorillo** [comment]
Let me know if you run into any problems, but I'm going to go ahead and close this.

**Comment by shanegriffiths** [comment]
Thanks Andrew, that's good to know. Perhaps you could add the current support on the read me file? Could avoid future questions about this.

Many thanks
S
